# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dbus-1 library
      run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev

    - name: lib-debug
      run: cmake --preset lib-debug

    - name: Build lib-debug
      run: cmake --build ${{github.workspace}}/build

    - name: lib-release
      run: cmake --preset lib-release

    - name: Build lib-debug
      run: cmake --build ${{github.workspace}}/build

    - name: example
      run: cmake --preset example

    - name: Build lib-debug
      run: cmake --build ${{github.workspace}}/build
